### ISSUE TITLE
No address associated with hostname

### ISSUE THREAD

**Issue by gzurbach** [thumbor/remotecv#16]
Hi there, sorry if this is not the right place to ask this question. I spent a few hours configuring Thumbor and got it to work. I am not trying to add remotcv and I am running into a issue.

Here are the logs (I removed some lines for clarity):
```
thumbor_1   | 2017-07-03 02:07:28 tornado.access:INFO 304 GET /unsafe/250x250/smart/photos/users/525f471da20c31e67432a3df45129b38.jpg (172.19.0.4) 90.80ms
[...]
remotecv_1  | INFO:remotecv:Detecting all for photos/users/525f471da20c31e67432a3df45129b38.jpg
remotecv_1  | ERROR:pyres.worker:(Job{Detect} | remotecv.pyres_tasks.DetectTask | [u'all', u'photos/users/525f471da20c31e67432a3df45129b38.jpg', u'photos/users/525f471da20c31e67432a3df45129b38.jpg']) failed: <urlopen error [Errno -5] No address associated with hostname>
remotecv_1  | Traceback (most recent call last):
remotecv_1  |   File "/usr/local/lib/python2.7/site-packages/pyres/worker.py", line 253, in process
remotecv_1  |     return job.perform()
remotecv_1  |   File "/usr/local/lib/python2.7/site-packages/pyres/job.py", line 55, in perform
remotecv_1  |     return payload_class.perform(*args)
remotecv_1  |   File "/usr/local/lib/python2.7/site-packages/remotecv/pyres_tasks.py", line 12, in perform
remotecv_1  |     image_data = config.loader.load_sync(image_path)
remotecv_1  |   File "/usr/local/lib/python2.7/site-packages/remotecv/http_loader.py", line 8, in load_sync
remotecv_1  |     return urllib2.urlopen(path).read()
remotecv_1  |   File "/usr/local/lib/python2.7/urllib2.py", line 154, in urlopen
remotecv_1  |     return opener.open(url, data, timeout)
remotecv_1  |   File "/usr/local/lib/python2.7/urllib2.py", line 429, in open
remotecv_1  |     response = self._open(req, data)
remotecv_1  |   File "/usr/local/lib/python2.7/urllib2.py", line 447, in _open
remotecv_1  |     '_open', req)
remotecv_1  |   File "/usr/local/lib/python2.7/urllib2.py", line 407, in _call_chain
remotecv_1  |     result = func(*args)
remotecv_1  |   File "/usr/local/lib/python2.7/urllib2.py", line 1228, in http_open
remotecv_1  |     return self.do_open(httplib.HTTPConnection, req)
remotecv_1  |   File "/usr/local/lib/python2.7/urllib2.py", line 1198, in do_open
remotecv_1  |     raise URLError(err)
remotecv_1  | URLError: <urlopen error [Errno -5] No address associated with hostname>
```

I deployed everything using [docker-thumbor](https://github.com/APSL/docker-thumbor). My images are hosted in AWS S3. I assume that the issue is coming from `remotecv` not being able to get the file.

Here si my config:
```
REMOTECV_REDIS_HOST=redis
REMOTECV_REDIS_PORT=6379
REMOTECV_REDIS_DATABASE=0
LOADER=remotecv_aws.loader
AWS_ACCESS_KEY_ID=xxxx
AWS_SECRET_ACCESS_KEY=xxxx
AWS_REGION=us-east-1
AWS_LOADER_BUCKET=xxx
```

Any suggestion? I am not sure that `AWS_REGION` is the valid option. I can't find proper documentation. I'd appreciate any input!

**Comment by eduherraiz** [comment]
You need to configure remotecv to use a custom aws loader.

**Comment by gzurbach** [comment]
Isn't what `LOADER=remotecv_aws.loader` is supposed to do? Could you point out to me an example of configuration for remotecv that fetches images from S3?

**Comment by gzurbach** [comment]
It looks like `remotecv_aws` only takes a bucket and a region but no key/secret. Does it means that the module only supports public buckets?
Either way, my images are all public in the bucket so I don't think it is related to auth.

I thought this would be enough:
```
LOADER=remotecv_aws.loader
AWS_REGION=us-east-1
AWS_LOADER_BUCKET=my-bucket
```

**Comment by clyquan** [comment]
remotecv didn't support TC_AWS_ENDPOINT ,  TC_AWS_LOADER_BUCKET ?
