### ISSUE TITLE
Remotecv can't fetch url with `%20` in it

### ISSUE THREAD

**Issue by RaphaelVRossi** [thumbor/remotecv#55]
When remotecv fetchs a new image from URL, it decode from `urlEncoded` to normal text, transforming `%20` into `whitespace` 

URL:  http://domain.org/my%20image.jpeg

```python
ERROR:pyres.worker:(Job{Detect} | remotecv.pyres_tasks.DetectTask | ['face+profile+glass', 'http%3A//domain.org/my%20image.jpeg', 'http%3A//domain.org/my%20image.jpeg']) failed: URL can't contain control characters. 'my  image.jpeg' (found at least ' ')
Traceback (most recent call last):
  File "/home/application/python/lib/python3.9/site-packages/pyres/worker.py", line 256, in process
    return job.perform()
  File "/home/application/python/lib/python3.9/site-packages/pyres/job.py", line 83, in perform
    return payload_class.perform(*args)
  File "/home/application/python/lib/python3.9/site-packages/remotecv/pyres_tasks.py", line 17, in perform
    image_data = config.loader.load_sync(image_path)
  File "/home/application/python/lib/python3.9/site-packages/thumbor/loaders/http_loader.py", line 62, in load_sync
    return urllib.request.urlopen(sanitized_path).read()
  File "/home/application/python/lib/python3.9/urllib/request.py", line 214, in urlopen
    return opener.open(url, data, timeout)
  File "/home/application/python/lib/python3.9/urllib/request.py", line 517, in open
    response = self._open(req, data)
  File "/home/application/python/lib/python3.9/urllib/request.py", line 534, in _open
    result = self._call_chain(self.handle_open, protocol, protocol +
  File "/home/application/python/lib/python3.9/urllib/request.py", line 494, in _call_chain
    result = func(*args)
  File "/home/application/python/lib/python3.9/urllib/request.py", line 1371, in http_open
    return self.do_open(http.client.HTTPConnection, req)
  File "/home/application/python/lib/python3.9/urllib/request.py", line 1342, in do_open
    h.request(req.get_method(), req.selector, req.data, headers,
  File "/home/application/python/lib/python3.9/http/client.py", line 1255, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "/home/application/python/lib/python3.9/http/client.py", line 1266, in _send_request
    self.putrequest(method, url, **skips)
  File "/home/application/python/lib/python3.9/site-packages/sentry_sdk/integrations/stdlib.py", line 86, in putrequest
    rv = real_putrequest(self, method, url, *args, **kwargs)
  File "/home/application/python/lib/python3.9/http/client.py", line 1100, in putrequest
    self._validate_path(url)
  File "/home/application/python/lib/python3.9/http/client.py", line 1200, in _validate_path
    raise InvalidURL(f"URL can't contain control characters. {url!r} "
http.client.InvalidURL: URL can't contain control characters. 'my  image.jpeg' (found at least ' ')
```

**Comment by heynemann** [comment]
That's expected @RaphaelVRossi ... That url is broken. The URL that should be passed to thumbor should be that one encoded again. Thumbor has to decode URLs to request. This issue has popped many times in the past.

The process is:
1. Get the URL your server needs to receive and encode that to send to your server (so that the server can understand it)
2. Now encode it again for when thumbor calls the server. 

I know this double encoding is weird, but it's the only way we can ensure both thumbor and the remote server can understand URLs with special characters like whitespace.
